# Generated by Django 5.1.2 on 2024-11-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scheduledemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_list', models.TextField()),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField()),
            ],
        ),
    ]
